### ISSUE TITLE
Upload to spacedock.info

### ISSUE THREAD

**Issue by linuxgurugamer** [OakTree42/KSI-Hiring#4]
Please upload to spacedock, and get the netkan updated.

I'd be happy to do so for you, just need your permission and notification to spacedock people that it's ok for me to do so

**Comment by OakTree42** [comment]
This was done, but is only for 1.0.5. So I need to update it, and that will take time. So not a matter of upload, the old version is on space dock. Closing issue for now. As soon as I have a valid update for 1.1.2 I will upload /that/.
